/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBairrosRouteImport } from './routes/_authenticated/bairros'
import { Route as AuthenticatedCaptarRouteImport } from './routes/_authenticated/captar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRuasRouteImport } from './routes/_authenticated/ruas'
import { Route as AuthenticatedSegmentosRouteImport } from './routes/_authenticated/segmentos'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBairrosRoute = AuthenticatedBairrosRouteImport.update({
  id: '/bairros',
  path: '/bairros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaptarRoute = AuthenticatedCaptarRouteImport.update({
  id: '/captar',
  path: '/captar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRuasRoute = AuthenticatedRuasRouteImport.update({
  id: '/ruas',
  path: '/ruas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSegmentosRoute = AuthenticatedSegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof AuthenticatedBairrosRoute
  '/captar': typeof AuthenticatedCaptarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/ruas': typeof AuthenticatedRuasRoute
  '/segmentos': typeof AuthenticatedSegmentosRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof AuthenticatedBairrosRoute
  '/captar': typeof AuthenticatedCaptarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/ruas': typeof AuthenticatedRuasRoute
  '/segmentos': typeof AuthenticatedSegmentosRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bairros': typeof AuthenticatedBairrosRoute
  '/_authenticated/captar': typeof AuthenticatedCaptarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/ruas': typeof AuthenticatedRuasRoute
  '/_authenticated/segmentos': typeof AuthenticatedSegmentosRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bairros'
    | '/captar'
    | '/dashboard'
    | '/produtos'
    | '/ruas'
    | '/segmentos'
    | '/leads/$id'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bairros'
    | '/captar'
    | '/dashboard'
    | '/produtos'
    | '/ruas'
    | '/segmentos'
    | '/leads/$id'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bairros'
    | '/_authenticated/captar'
    | '/_authenticated/dashboard'
    | '/_authenticated/produtos'
    | '/_authenticated/ruas'
    | '/_authenticated/segmentos'
    | '/_authenticated/leads/$id'
    | '/_authenticated/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bairros': {
      id: '/_authenticated/bairros'
      path: '/bairros'
      fullPath: '/bairros'
      preLoaderRoute: typeof AuthenticatedBairrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/captar': {
      id: '/_authenticated/captar'
      path: '/captar'
      fullPath: '/captar'
      preLoaderRoute: typeof AuthenticatedCaptarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ruas': {
      id: '/_authenticated/ruas'
      path: '/ruas'
      fullPath: '/ruas'
      preLoaderRoute: typeof AuthenticatedRuasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/segmentos': {
      id: '/_authenticated/segmentos'
      path: '/segmentos'
      fullPath: '/segmentos'
      preLoaderRoute: typeof AuthenticatedSegmentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBairrosRoute: typeof AuthenticatedBairrosRoute
  AuthenticatedCaptarRoute: typeof AuthenticatedCaptarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRuasRoute: typeof AuthenticatedRuasRoute
  AuthenticatedSegmentosRoute: typeof AuthenticatedSegmentosRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBairrosRoute: AuthenticatedBairrosRoute,
  AuthenticatedCaptarRoute: AuthenticatedCaptarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRuasRoute: AuthenticatedRuasRoute,
  AuthenticatedSegmentosRoute: AuthenticatedSegmentosRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
